spring.application.name=payment-service
server.port=8086
spring.mongodb.uri=mongodb+srv://erolldilo5:a3p8qlDIwCoLnTRj@cluster0.uwnx77z.mongodb.net/?appName=Cluster0
spring.mongodb.database=skillshare
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
