spring.application.name=payment-service
server.port=8085
spring.mongodb.uri=mongodb+srv://erolldilo5:dIaoPFxLtNAxj5hR@cluster0.uwnx77z.mongodb.net/?appName=Cluster0
spring.mongodb.database=skillshare
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
